theme: jekyll-theme-architect
# Google Analytics
google_analytics: UA-114692803-1
show_downloads: false
title: <img src="assets/imgs/shortcode.png" />
description: tips, tutorials and arcticles<br/>on crafting software
